### ISSUE TITLE
README docker instructions

### ISSUE THREAD

**Issue by trey-stafford** [ropensci/smapr#54]
The README's docker instructions are incomplete.

Running the supplied docker command exits without failure (exit status 0), potentially leaving the user confused as to what happened.

Attempting to run the command in the foreground (remove `-d` flag: `docker run -p 8787:8787 earthlab/smapr`) reveals that I was not supplying a required environment variable, `PASSWORD`.

May want to link directly to the documentation for the `earthlab/smapr` Docker image (https://github.com/earthlab/dockerfiles/tree/master/smapr#how-to-use) in the README.

**Comment by mbjoseph** [comment]
Thanks @trey-stafford - good catch! Fixed with 33bcd17fa7ca37eaa9d10cf0b397c709e984be63
