### ISSUE TITLE
Error in Curl when Fetching Data

### ISSUE THREAD

**Issue by MDunsker** [ropensci/smapr#58]
Here is the code I am using to download one observation of SMAP for every day within a given window:

date.code <- seq(as.Date("2015/07/26"), as.Date("2015/12/31"), by = 1)

for(i in 1:length(date.code)){
  newName = paste0('SMAP_', date.code[i], '_time12.tif') #Create Unique Filename
  SMAP_data <- find_smap(id= "SPL4SMAU", date = date.code[i], version = 4)
  SMAP_noon <- SMAP_data[c(4),] #Index SMAP data to get 4th observation, at time = 12
  SMAP_download <- download_smap(SMAP_noon) #Download SMAP t = 12 observation
  SMAP_raster <- extract_smap(SMAP_download, "/Analysis_Data/sm_rootzone_analysis")
  SMAP_reproj <- projectRaster(SMAP_raster, crs = "+init=epsg:4326 +proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0") #Reproject SMAP Raster into WGS84
  SMAP_mask <- mask(SMAP_reproj, roi_mask) #Mask
  SMAP_crop <- crop(SMAP_mask, roi_mask) #Crop
  rf <- writeRaster(x=SMAP_crop, filename=newName, format = "GTiff", overwrite=T) #Store
}

It has worked many times over the past month, however occasionally I am running into the same error, which seems to occur after I have downloaded a lot of imagery for one day.

The error is this:
Error in curl::curl_fetch_disk(url, x$path, handle = handle) : 
  Failed writing body (2252 != 16060)

The number preceding the != operator changes between error results however.

Please let me know if you know why this is occurring! We are attempting to use the SMAPR package for a project for NASA DEVELOP and will be unable to use it if it cannot reliably retrieve SMAP imagery.

Thank you!
Max Dunsker
maxdunsker@gmail.com

**Comment by mbjoseph** [comment]
@MDunsker thanks for opening this issue. I was not able to reproduce the error that you are seeing. 

My best guess is that this error is being raised when actually downloading the file, when this line is executed: https://github.com/ropensci/smapr/blob/master/R/download_smap.R#L121 which then raises the curl error via the `httr` package: https://github.com/r-lib/httr/blob/master/R/write-function.R#L82

If so, then this may be an httr or curl issue, or something happening intermittently server-side where the data are stored. If true, the `extract_smap`, `projectRaster`, `mask`, `crop`, and `writeRaster` operations may not be relevant to the issue. 

Does this reliably happen for the same file (e.g., the same value of `i` in your loop)? If so, that would be helpful for debugging the issue.

**Comment by MDunsker** [comment]
@mbjoseph thank you for taking the time to answer the question, I really appreciate it. I figured out that the problem was being caused due to a lack of space on my C: drive, even though I was saving the files to my E: drive. The problem is now solved!

**Comment by mbjoseph** [comment]
Great!
