### ISSUE TITLE
Unable to download SMAP_L3_SM_P_20190801_R16022_001

### ISSUE THREAD

**Issue by abhishekmisra2020** [ropensci/smapr#59]
Writing below code and getting following error please help me
Regards
Abhishek

>library(smapr)
> library(raster)
> find_smap(id = "SPL3SMP", date = "2019-08-01", version = 5)
                              name       date                     dir
1 SMAP_L3_SM_P_20190801_R16022_001 2019-08-01 SPL3SMP.005/2019.08.01/
> download_smap()
Error in validate_input_df(files) : 
  argument "files" is missing, with no default
> download_smap("SMAP_L3_SM_P_20190801_R16022_001 2019-08-01 SPL3SMP.005/2019.08.01/")
Error in vector(mode = "list", length = n_downloads) : 
  invalid 'length' argument
> download_smap("SMAP_L3_SM_P_20190801_R16022_001")
Error in vector(mode = "list", length = n_downloads) : 
  invalid 'length' argument

**Comment by mbjoseph** [comment]
Hi @abhishekmisra2020 -- you are close to getting this to work, but the syntax in your example is a bit off. Here's how to get that data: 

``` r
library(smapr)

# 1. Find the files that are available
files <- find_smap(id = "SPL3SMP", date = "2019-08-01", version = 5)

# 2. Download those data files
downloads <- download_smap(files)
#> Downloading https://n5eil01u.ecs.nsidc.org/SMAP/SPL3SMP.005/2019.08.01/SMAP_L3_SM_P_20190801_R16022_001.h5
#> Downloading https://n5eil01u.ecs.nsidc.org/SMAP/SPL3SMP.005/2019.08.01/SMAP_L3_SM_P_20190801_R16022_001.qa
#> Downloading https://n5eil01u.ecs.nsidc.org/SMAP/SPL3SMP.005/2019.08.01/SMAP_L3_SM_P_20190801_R16022_001.h5.iso.xml

# 3. Extract soil moisture as a raster object
rast <- extract_smap(downloads, 
                     name = "Soil_Moisture_Retrieval_Data_AM/soil_moisture")
```

<sup>Created on 2019-08-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

For more examples, see the documentation: https://ropensci.github.io/smapr/
