### ISSUE TITLE
Error in curl

### ISSUE THREAD

**Issue by wsn19930220** [ropensci/smapr#68]
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached: [urs.earthdata.nasa.gov] Connection timed out after 10000 milliseconds

**Comment by mbjoseph** [comment]
Hi @wsn19930220 - can you please make a reprex: https://reprex.tidyverse.org/ and paste your session information in this issue?

**Comment by mbjoseph** [comment]
Closing this for now - can't reproduce.
