### ISSUE TITLE
pre-build vignette?

### ISSUE THREAD

**Issue by maelle** [ropensci/smapr#70]
:wave: @mbjoseph!

On rOpenSci [docs server](https://ropensci.org/blog/2021/09/03/runiverse-docs/) the pkgdown website of your package can't be built  https://github.com/r-universe/ropensci/runs/4511976862?check_suite_focus=true

```r
Reading 'vignettes/smapr-intro.Rmd'
-- RMarkdown error -------------------------------------------------------------
Quitting from lines 85-86 (smapr-intro.Rmd) 
Error in check_creds() : 
  smapr expected ed_un and ed_pw to be environment variables!
The smapr package requires a username and password from
NASA's Earthdata portal.

If you have a username and password please provide them with
the set_smap_credentials() function, e.g.,
set_smap_credentials('username', 'passwd')

If you do not have a username and password, get one here:
urs.earthdata.nasa.gov
--------------------------------------------------------------------------------
Error : Failed to render RMarkdown
```

You could [precompute](https://ropensci.org/blog/2019/12/08/precompute-vignettes/) the vignette. Happy to answer any question (but in 2022 :grin: )

**Comment by maelle** [comment]
wave @mbjoseph! friendly reminder :smile_cat:

**Comment by mbjoseph** [comment]
Oh hey @maelle! 😅 

It looks like there are no credentials found on the build server. Is there a way to provide an encrypted username and password (e.g., as environment variables) to the build? To me, this might be slightly preferable to precomputing the vignette. 

If there's no easy way to provide credentials, then I can work on the precomputed vignette!

**Comment by maelle** [comment]
Hello! :grinning: 

> If there's no easy way to provide credentials, then I can work on the precomputed vignette!

Indeed at the moment there's no way to provide credentials.
