### ISSUE TITLE
Extracting from a directory using extract_smap

### ISSUE THREAD

**Issue by RomanChapman** [ropensci/smapr#71]
Just wondering if there is documentation (or functionality) for extracting previously downloaded HDF5 data from a directory using extract_smap(data, name, in_memory = FALSE)

**Comment by mbjoseph** [comment]
I believe you can do this by specifying overwrite=FALSE in your call to download_smap with a user specified dir. See for example: https://github.com/ropensci/smapr/blob/master/tests/testthat/test-extract_smap.R#L61-L69
